[build]
  command = " yarn build"
  publish="/build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/*"
  to = "/build/index.html"
  status = 200